import { test, expect } from '../harness/fixtures';
import { enterGuestChat } from './helpers/guest';
import { sendStory, setContinuousEnabled, waitStoryCardReady, startNewStoryCollection, openExpandedFromMini, closeExpanded, composerInput, captureVisual } from './helpers/creation-journey';

/** 用可见页面完成单篇整理、整集恢复、历史续写与回听。 */
test('整理故事并回到原集续写和收听', async ({ page, harnessEnv }) => {
  test.setTimeout(300000);
  await enterGuestChat(page, harnessEnv.appUrl);
  await setContinuousEnabled(page, false);
  await sendStory(page, '写一个关于藏在树梢上的邮局的故事');
  await waitStoryCardReady(page, 0);
  await sendStory(page, '写一个关于海边灯塔的故事');
  await waitStoryCardReady(page, 1);
  const title = (await page.getByTestId('continuous-collection-title').innerText()).trim();
  await page.getByTestId('continuous-collection-title').getByRole('link').click();
  await page.waitForURL(/\/library\/collections\/[^/]+$/);
  const groupUrl = page.url();
  const members = page.getByTestId(/^member-work-/);
  await expect(members).toHaveCount(2);
  const firstTitle = (await members.first().getByRole('heading').innerText()).trim();
  await members.first().getByText('更多', { exact: true }).click();
  await members.first().getByRole('button', { name: '收藏单篇', exact: true }).click();
  await expect(members.first().getByRole('button', { name: '取消收藏单篇' })).toBeVisible();
  await page.getByRole('tab', { name: '故事库', exact: true }).click();
  await page.getByRole('tab', { name: '收藏', exact: true }).click();
  await page.waitForURL('**/library/favorites');
  await page.getByRole('link', { name: '单篇故事', exact: true }).click();
  await expect(page.getByRole('heading', { name: firstTitle, exact: true })).toBeVisible();
  await page.getByRole('link', { name: firstTitle, exact: true }).click();
  await page.waitForURL(/\/collections\/[^/]+\/works\/\d+$/);
  await page.getByRole('link', { name: `返回《${title}》`, exact: true }).click();
  await members.first().getByText('更多', { exact: true }).click();
  await members.first().getByRole('button', { name: '移入回收站', exact: true }).click();
  await expect(members).toHaveCount(1);
  await page.getByText('管理故事集', { exact: true }).click();
  await page.getByTestId('collection-delete-btn').click();
  await page.getByRole('tab', { name: '回收站', exact: true }).click();
  await page.waitForURL('**/library/trash');
  await page.getByRole('button', { name: `恢复作品集《${title}》` }).click();
  await page.getByRole('tab', { name: '全部', exact: true }).click();
  await page.getByRole('link', { name: title, exact: true }).click();
  await expect(members).toHaveCount(1);
  await page.getByRole('tab', { name: '故事库', exact: true }).click();
  await page.getByRole('tab', { name: '回收站', exact: true }).click();
  await page.getByRole('link', { name: '单篇故事', exact: true }).click();
  await page.getByRole('button', { name: `恢复《${firstTitle}》`, exact: true }).click();
  await page.goto(groupUrl);
  await expect(members).toHaveCount(2);
  await page.getByRole('link', { name: '查看创作记录', exact: true }).click();
  await page.waitForURL('**/chat/conversations/**');
  await page.getByRole('button', { name: '返回创作', exact: true }).click();
  await startNewStoryCollection(page);
  await setContinuousEnabled(page, false);
  await composerInput(page).fill('保留这份新主题草稿');
  await page.getByRole('tab', { name: '故事库', exact: true }).click();
  await page.getByRole('link', { name: title, exact: true }).click();
  await page.getByRole('link', { name: '查看创作记录', exact: true }).click();
  await page.waitForURL('**/chat/conversations/**');
  await page.getByRole('button', { name: '续写这个故事集', exact: true }).click();
  await page.getByRole('button', { name: '保留草稿并切换', exact: true }).click();
  await page.waitForURL('**/chat');
  await expect(page.getByTestId('continuous-collection-title')).toHaveText(title);
  await expect(page.getByRole('switch', { name: '连续创作开关' })).not.toBeChecked();
  await sendStory(page, '续写这个故事集，让邮差回到灯塔');
  await waitStoryCardReady(page, 2);
  await page.getByTestId('continuous-collection-title').getByRole('link').click();
  await expect(members).toHaveCount(3);
  await page.getByRole('button', { name: '从头听整集', exact: true }).click();
  await openExpandedFromMini(page);
  await expect(page.getByRole('region', { name: '集内播放列表' })).toBeVisible();
  await expect(page.getByText('整集回听 · 第 1 / 3 篇')).toBeVisible();
  await page.getByRole('slider', { name: '播放进度', exact: true }).focus();
  await page.keyboard.press('End');
  await expect(page.getByText('整集回听 · 第 2 / 3 篇')).toBeVisible({ timeout: 60000 });
  await page.getByRole('button', { name: '下一篇', exact: true }).click();
  await expect(page.getByText('整集回听 · 第 3 / 3 篇')).toBeVisible({ timeout: 60000 });
  await closeExpanded(page);
  await page.setViewportSize({ width: 375, height: 812 });
  await captureVisual(page, 'library-manage-resume-mobile');
});
